FROM python:3.9

WORKDIR /app


# RUN apt-get update && apt-get install -y ffmpeg

# Copy the requirements and install dependencies
COPY requirements.txt ./app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install "fastapi[standard]"
RUN pip install "joblib"
RUN pip install "pandas"
# Copy the FastAPI code into the container
COPY ./app/fastapi /app/fastapi/

# Expose the correct port for Cloud Run
EXPOSE 8000

#WORKDIR /app/
# Start the FastAPI app with Uvicorn
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
# CMD ["uvicorn", "app.fastapi.main:app", "--host", "0.0.0.0", "--port", "8000"]
#CMD ["fastapi", "run", "app/fastapi/main.py", "--server.port", "8000", "--server.address", "0.0.0.0"]
CMD ["python", "fastapi/fastapi_main.py"]